services:
  openstock:
    image: openstock-app:latest
    container_name: openstock-app
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    extra_hosts:
      - "mongodb:host-gateway"
